services:
  fastapi:
    build: .
    user: "0:0"
    restart: always
    container_name: bot_echo
    ports:
      - "8082:8082"
    volumes:
      - ./logs:/app/logs
    env_file: .env
    networks:
      - bot_network

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: echo_bot_cloudflared
    restart: always
    depends_on:
      - fastapi
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN:-""}
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge
